# Lab exercise, week 3 - numpy & matplotlib basics

Contents:
- Overview of numpy arrays
- Exercises for numpy
- Exercises for plotting

## NumPy - overview

Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [2]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [ ]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [ ]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [ ]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [ ]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [ ]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.14654318, 0.24300736, 0.74564537, 0.58652819, 0.39433085,
       0.94389319])

In [ ]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([64, 97,  1, 69, 74, 72])

### Array properties

In [ ]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [ ]:
# Data type of the array
a.dtype

dtype('int64')

In [ ]:
# number of dimensions
b.ndim

2

In [ ]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [ ]:
# The total number of elements
b.size

6

In [ ]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [ ]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


### Numpy Array Creation

##### Convert a list into a numpy array

In [ ]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [ ]:
# your code here
x =
x

#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [ ]:
# Feel free to add more cells


#### Create an array of 10 ones [1, 1, 1, ... ]

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives [5, 5, 5, .... ]

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (including 50)

In [ ]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of 10 random numbers between 0 and 5

array([4.1768665 , 1.07033279, 0.7846438 , 3.18405681, 1.27260556,
       2.43195879, 4.63388763, 1.91023326, 1.03926283, 3.61216094])

#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2
use `np.linspace?` or `?np.linspace` to show the help

In [ ]:
np.linspace(0, 2, 11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

#### Create a 3 by 4 array of ones

In [19]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Create a 3 by 4 array of fives

In [ ]:
np.ones((3, 4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

### Array Indexing
Using the following arrays `a` and `m` for the questions below

In [ ]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
m = np.arange(1,22).reshape((3,7))
m

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Create an array containing...
#### the first 4 elements of a

In [ ]:
a[:4]

array([10, 11, 12, 13])

#### the last 3 elements of a

In [ ]:
a[-3:]

array([18, 19, 20])

#### The middle elements of a from 15 to 18 inclusive

In [ ]:
a[(a >= 15) & (a <= 18)]

array([15, 16, 17, 18])

#### The first column of m

In [ ]:
m[:, 0]

array([ 1,  8, 15])

#### The middle row of m

In [ ]:
m[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

#### The left 3 columns of m

In [ ]:
m[:,-3:]

array([[ 5,  6,  7],
       [12, 13, 14],
       [19, 20, 21]])

#### The bottom-right 2 by 2 square

In [16]:
m[1:,-2]

array([13, 20])

#### Print every other element of a
Hint: use slicing with a step (`array[start:stop:step]`)

In [17]:
a[::2]

array([10, 12, 14, 16, 18, 20])

#### Print the `even` elements of a
Hint: use boolean indexing

In [18]:
mask=a%2==0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [ ]:
a[mask]

### Array Math

#### Subtract 5 from each element of a

In [15]:
a = np.arange(10,21)

In [20]:
display(a - 5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Calculate the `sum` of all the elements in a

In [10]:
display(a.sum())

np.int64(165)

#### Calculate the sum of each column and each row in `m`
Hint: use the `axis` argument of the `sum` method

In [21]:
display(m.sum(axis=0)) # sum of columns
display(m.sum(axis=1)) # sum of rows

array([24, 27, 30, 33, 36, 39, 42])

array([ 28,  77, 126])

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

In [23]:
display(np.arange(1, 11)**2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

In [24]:
display(2**np.arange(11))

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

In [25]:
display(2**np.arange(11) - 1)

array([   0,    1,    3,    7,   15,   31,   63,  127,  255,  511, 1023])

## Plotting Basics
 - Use [this tutorial](https://matplotlib.org/users/pyplot_tutorial.html) as reference when (if) you get stuck
 - Execute the cells with imports, otherwise you won't have numpy and matplotlib imported and Python will complain

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Load weather data (take a look at that CSV file on GitHub or via Excel and note column names)
weather = np.loadtxt("OshawaWeather2016.csv", skiprows=1, delimiter=',')

In [ ]:
weather.shape

(349, 5)

In [ ]:
weather.dtype

dtype('float64')

#### Crate separate 1D arrays for each column (e.g: day, maxt, mint and so on)

In [ ]:
# your code here
# column name in csv file: Day,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Total Precip (mm)
# day = weather[???]


#### Plot the minimum temperature as a function of day number

#### Plot the max temperature in degrees Fahrenheit

#### Plot the difference between the maximum and the minimum day temperature as a function of day number

#### Plot both, the minimum and maximum temperature on the same figure

#### Add axis labels and a legend to the plot above
Use the following functions:
 - plt.xlabel
 - plt.ylabel
 - plt.title
 - plt.legend

#### Read about plt.hist() function and plot a histogram of the maximum temperatures

In [ ]:
plt.hist?

#### Plot a histogram of the differences between the min and max temperature

#### For each day calculate the average of the 3 temperatures in the data (min max and avg)


#### Calculate the total amount of precipitation for the whole year
Does the number seem reasonable? The annual average precipitation in Toronto is 831 mm according to https://en.wikipedia.org/wiki/Geography_of_Toronto

#### Calculate the total precipitation on all odd numbered days (day 1, 3, 5 and so on)